iwate: イーハトーブ岩手電子図書館
rih05: 生態史写真資料
kennai: 三重県内の博物館資料館
nin03: 日本言語地図
kuhi: 三重県内の句碑
nin02: 方言文法全国地図
Nhikie: 蚕織錦絵コレクション
machihaku: 三重県まちかど博物館
aomori: 青森県立図書館デジタルアーカイブ
gunma: 群馬県立図書館デジタルライブラリー
narabook: まほろばデジタルライブラリー
miebunkazai: 三重県内の指定文化財
tfam_art_db: 東京富士美術館収蔵品データベース
rih06: 生態史文献資料
kochizu_collection: 古地図コレクション
irc05: 在外日本美術データベース
irc03: 平安京都名所図会
chiba: 千葉県デジタルアーカイブ
nij09: 歴史人物画像データベース
michi: みちしる
keio: 慶應デジタルコレクション
irc04: 季語検索
shisan: 三重の歴史文化散策マップ
sapporo: 札幌市中央図書館デジタルライブラリー
nij06: 欧州所在日本古書総合目録
nfad: NFAJ所蔵映画フィルム検索システム
apmoa_mapps: 愛知県美術館コレクション
photo: 写真原板データベース
nin04: 米国議会図書館本源氏物語翻字
a12345: データカタログサイト
bunka: 文化遺産オンライン
nij04: 二十一代集データベース
nij02: 吾妻鏡データベース
syozo: 国立美術館所蔵作品総合目録
nij03: 絵入源氏物語